name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Checking package dependencies
        run: make ci
      - name: shellcheck
        run: make shellcheck
