name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy Symlink to Home Directory
        run: ./setup.sh
      - name: Install brew bundle packages
        run: brew bundle
      - name: Install Vim Plugin via dein.vim
        run: vim -N -u ~/.vim/init.vim -c "try | call dein#install() | finally | qall! | endtry" -V1 -es
