name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Copy Symlink to Home Directory
        run: python setup.py
      - name: Install brew bundle packages
        run: brew bundle
